### ISSUE TITLE
Client crashes when opening the map (M)

### ISSUE THREAD

**Issue by FauEr7** [gwdevhub/Daybreak#883]
Windows 11

Client crashes in the exact moment I press M. 

I tried it with the same texmods and toolbox, but without daybreak and the Map (M) opens normally. 
I paused all Antivirus, restarted the system but no change in behavior.

Below is the log. Happy to help if you need more information.

`[27.11.2024 14:00:26 +00:00]	[Error]	[Daybreak.Services.Scanner.GWCAMemoryReader]	[1QsMIDflnEKo4JK2.222]
ReadLoginData: Encountered exception while parsing response
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen..
 ---> System.Net.Sockets.SocketException (995): Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|4_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Daybreak.Utils.MetricsHttpMessageHandler`1.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Daybreak.Services.GWCA.GWCAClient.GetAsync(ConnectionContext connectionContext, String subPath, CancellationToken cancellationToken)
   at Daybreak.Services.Scanner.GWCAMemoryReader.ReadLoginData(CancellationToken cancellationToken)

[27.11.2024 14:00:26 +00:00]	[Information]	[Daybreak.Services.ExceptionHandling.ExceptionHandler]	[1QsMIDflnEKo4JK2.223]
Encountered TaskCanceledException. Ignoring
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Daybreak.Controls.Templates.LaunchButtonTemplate.PeriodicallyCheckGameState(CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[27.11.2024 14:00:28 +00:00]	[Information]	[Daybreak.Services.Graph.GraphClient]	[1QsMIDflnEKo4JK2.224]
Sending HTTP request GET https://graph.microsoft.com/v1.0/me/drive/root:/Daybreak/Settings/daybreak.json:/content

[27.11.2024 14:00:28 +00:00]	[Trace]	[Daybreak.Services.Graph.GraphClient]	[1QsMIDflnEKo4JK2.225]
Request Headers:
User-Agent: *
Accept: *

[27.11.2024 14:00:28 +00:00]	[Information]	[Daybreak.Services.Graph.GraphClient]	[1QsMIDflnEKo4JK2.226]
Received HTTP response headers after 15.6583ms - 401

[27.11.2024 14:00:28 +00:00]	[Trace]	[Daybreak.Services.Graph.GraphClient]	[1QsMIDflnEKo4JK2.227]
Response Headers:
Transfer-Encoding: *
Strict-Transport-Security: *
request-id: *
client-request-id: *
x-ms-ags-diagnostic: *
WWW-Authenticate: *
Date: *
Content-Type: *

[27.11.2024 14:00:28 +00:00]	[Information]	[Daybreak.Services.Images.ImageCache]	[1QsMIDflnEKo4JK2.228]
[C:\Users\Vivian\Documents\Guild Wars\Screens\gw038.jpg] GetImage: Exceeding cache size. Freeing up 8834603 bytes

[27.11.2024 14:00:28 +00:00]	[Information]	[Daybreak.Services.Images.ImageCache]	[1QsMIDflnEKo4JK2.229]
[C:\Users\Vivian\Documents\Guild Wars\Screens\gw038.jpg] GetImage: New cache size: 93369600 bytes

[27.11.2024 14:00:28 +00:00]	[Information]	[Daybreak.Services.Images.ImageCache]	[1QsMIDflnEKo4JK2.230]
[C:\Users\Vivian\Documents\Guild Wars\Screens\gw038.jpg] GetImage: Added image to cache
`

**Comment by AlexMacocian** [comment]
Hey, thanks for the bug report. I'll try to investigate it further in the upcoming days. For now, can you go to Focus View settings and disable Focus View?
![image](https://github.com/user-attachments/assets/6e6d937e-05f7-42cf-939c-aff4aa9802c6)

![image](https://github.com/user-attachments/assets/532665dc-cab0-4a6d-9012-9fb13c9cdcc4)

That should stop Daybreak from interfering at all with Toolbox's functionality and stop the crashes.

Please try to run it with Focus View disabled and let me know if the issue persists.


I'll notify here when I'll have a fix ready and a new release

**Comment by FauEr7** [comment]
Thanks a lot. It worked no more crashes. 
Sorry for offtopic but is there a way to autosave changes when there are made? The UX with pressing the save icon after every change is kinda frustrating.

**Comment by AlexMacocian** [comment]
I've removed the dependency on GWCA so that it no longer interferes with toolbox (and causes crashing on map. You should no longer experience crashes with Focus View on the latest version.
Daybreak no longer injects anything into GW, I've changed it so that it instead constantly reads memory (similar to Cheat Engine) for the restricted features of Focus View
